### ISSUE TITLE
Erro ao executar a API

### ISSUE THREAD

**Issue by AlcindoSchleder** [AlcindoSchleder/flask_API#1]
A Api roda corretamente e mostra a página de documentação do swagger em http://17.0.0.1:5000/iciti-api/docs. Ao executar o método get um erro acontece com a seguinte mensagem:

**ERROR in app: Exception on /icity-api/home/1.0/ [GET]**
**TypeError: __init__() takes 1 positional argument but 2 were given**
```
Traceback (most recent call last):
  File "/opt/python/apis/flask_API/.env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/python/apis/flask_API/.env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/python/apis/flask_API/.env/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/python/apis/flask_API/.env/lib/python3.7/site-packages/flask/views.py", line 88, in view
    self = view.view_class(*class_args, **class_kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
127.0.0.1 - - "GET /icity-api/home/1.0/ HTTP/1.1" 500
```
A definição das rotas:
```python
# -*- coding: utf-8 -*-
from flask_restplus import Namespace
from server import icityServer
from workspaces.home import BaseRoutes

ns = Namespace(BaseRoutes.API_BASE_NAME, description='Print Hello Word')

@ns.route('/')
@ns.doc('Imprime o HelloWord na tela')
class HomeRoutes(BaseRoutes):

    def __init__(self):
        super(HomeRoutes, self).__init__()

    @ns.doc('envia mensagem hello word')
    def get(self):
        return "<h1>Home page with Blueprint!</h1>"

icityServer.icity_api.add_namespace(ns, path=BaseRoutes.PATH_API)

api_functions = HomeRoutes.as_view(BaseRoutes.API_BASE_NAME)
icityServer.icity_app.add_url_rule('/', view_func=api_functions, methods=['GET'])
```
creio que tenha algo a ver com a chamada neste ponto:
```python
api_functions = HomeRoutes.as_view(BaseRoutes.API_BASE_NAME)
icityServer.icity_app.add_url_rule('/', view_func=api_functions, methods=['GET'])
```
código de BaseRoute:
```python
# -*- coding: utf-8 -*-
from flask.views import MethodView
from common.helpers.operationResults import OperationResults
from server import icityServer

class BaseRoutes(MethodView, OperationResults):

    API_ROOT = icityServer.icity_prefix
    API_BASE_NAME = 'home'
    VERSION = '1.0'
    PREFIX_ROUTE = f'{API_ROOT}/{API_BASE_NAME}'
    PATH_API = f'{API_ROOT}/{API_BASE_NAME}/{VERSION}'

    def __init__(self):
        super(BaseRoutes, self).__init__()
        
    def get(self):
        raise NotImplementedError()
```
Observações: *icityServer.icity_prefix = "/icity-api"*

**Comment by AlcindoSchleder** [comment]
encontrado o erro: bastava declarar __init__(self, *args, **kwargs) no arquivo OperationResults.
Já está publicada a nova versão.
